version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - type: bind
        source: /root/.acme.sh/dymawonder.fr
        target: /certs
      - type: bind
        source: .
        target: /app
    depends_on:
      - fpm
    ports:
      - 80:80
      - 443:443
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pomme123;
    volumes:
      - type: volume
        source: dbprod
        target: /var/lib/mysql
  fpm:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - type: volume
        target: /app/vendor
      - type: bind
        target: /app
        source: .
    depends_on:
      - mysql

  node:
    build:
      context: .
      dockerfile: Dockerfile.encore.prod
    volumes:
      - type: volume
        target: /app/node_modules
      - type: bind
        target: /app
        source: .

volumes:
  dbprod:
